<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="17280" started-at="2019-04-26T15:38:47Z" finished-at="2019-04-26T15:39:04Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.github.sevcensokmen.eehotelbooking.runners.PositiveTest@2ac273d3]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Test" duration-ms="17280" started-at="2019-04-26T15:38:47Z" finished-at="2019-04-26T15:39:04Z">
      <class name="com.github.sevcensokmen.eehotelbooking.runners.PositiveTest">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.github.sevcensokmen.eehotelbooking.runners.PositiveTest@2ac273d3]" name="setUpClass" is-config="true" duration-ms="274" started-at="2019-04-26T16:38:47Z" finished-at="2019-04-26T16:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:com.github.sevcensokmen.eehotelbooking.runners.PositiveTest@2ac273d3]" name="setup" is-config="true" duration-ms="389" started-at="2019-04-26T16:38:47Z" finished-at="2019-04-26T16:38:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.github.sevcensokmen.eehotelbooking.runners.PositiveTest@2ac273d3]" name="feature" duration-ms="16362" started-at="2019-04-26T16:38:47Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2019-04-26T16:39:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Acceptance testing to validate delete customer is working.]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [true] but found [false]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.github.sevcensokmen.eehotelbooking.steps.DeleteCustomerSteps.i_shouldn_t_see_last_booking_of_the_list(DeleteCustomerSteps.java:31)
	at âœ½.Then I shouldn't see last booking of the list.(DeleteCustomer.feature:11)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:com.github.sevcensokmen.eehotelbooking.runners.PositiveTest@2ac273d3]" name="tearDownClass" is-config="true" duration-ms="107" started-at="2019-04-26T16:39:04Z" finished-at="2019-04-26T16:39:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.github.sevcensokmen.eehotelbooking.runners.PositiveTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
